package UI.Forms.QuestionDialog;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author alexanis
 */
public class QuestionPanel extends javax.swing.JPanel {

    private ButtonGroup buttonGroup = new ButtonGroup();
    /** Creates new form QuestionPanel */
    public QuestionPanel() {
        initComponents();
    }

    public void addAnswer(JRadioButton jrb) {
        jPanel2.add(jrb);
        buttonGroup.add(jrb);
    }

    public void setQuestion(String question) {
        jTextAreaQuestion.setText(question);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTextAreaQuestion = new JTextArea();
        jPanel2 = new JPanel();

        setLayout(new BorderLayout());

        jPanel1.setBorder(BorderFactory.createTitledBorder("Вопрос"));
        jPanel1.setLayout(new BorderLayout());

        jTextAreaQuestion.setColumns(20);
        jTextAreaQuestion.setEditable(false);
        jTextAreaQuestion.setFont(new Font("Dialog", 1, 14)); // NOI18N
        jTextAreaQuestion.setLineWrap(true);
        jTextAreaQuestion.setRows(5);
        jTextAreaQuestion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaQuestion);

        jPanel1.add(jScrollPane1, BorderLayout.CENTER);

        add(jPanel1, BorderLayout.CENTER);

        jPanel2.setBorder(BorderFactory.createTitledBorder("Ответы"));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.PAGE_AXIS));
        add(jPanel2, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaQuestion;
    // End of variables declaration//GEN-END:variables

}
