package UI.Forms.Domen;

import logic.product.Domen;
import logic.product.Value;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

public class ChangeDomenDialog extends javax.swing.JDialog
{

  private DomenPanel domenPanel = new DomenPanel();

  /** Creates new form NewJDialog */
  public ChangeDomenDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    myInitComponents();
    this.setLocation((parent.getWidth() - this.getWidth()) / 2 + parent.getX(), (parent.getHeight() - this.getHeight()) / 2 + parent.getY());
  }

  private void myInitComponents()
  {
    jPanel1.setLayout(new BorderLayout());
    jPanel1.add(domenPanel);
  }

  public void run(Domen domen, Value value)
  {
    setTitle("Редактирование доменов");
    domenPanel.refresh();
    domenPanel.selectDomen(domen);
    domenPanel.selectValue(value);
    setVisible(true);
  }

  public Domen getDomen()
  {
    return domenPanel.getCurrentDomen();
  }

  public Value getValue()
  {
    return domenPanel.getCurrentValue();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel8 = new JPanel();
    jButtonClose = new JButton();
    jPanel1 = new JPanel();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new Dimension(640, 480));

    jPanel8.setLayout(new BorderLayout());

    jButtonClose.setIcon(new ImageIcon(getClass().getResource("/Images/16x16/close.png"))); // NOI18N
    jButtonClose.setText("Закрыть");
    jButtonClose.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jButtonCloseActionPerformed(evt);
      }
    });
    jPanel8.add(jButtonClose, BorderLayout.CENTER);

    getContentPane().add(jPanel8, BorderLayout.SOUTH);

    jPanel1.setBorder(BorderFactory.createEtchedBorder());

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 764, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 546, Short.MAX_VALUE)
    );

    getContentPane().add(jPanel1, BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton jButtonClose;
  private JPanel jPanel1;
  private JPanel jPanel8;
  // End of variables declaration//GEN-END:variables
}
