package UI.Forms.Domen;

import logic.product.Domen;
import logic.frames.Frameset;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

public class DomenDialog extends javax.swing.JDialog
{

  private Domen domen;

  /** Creates new form StringDialog1 */
  public DomenDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    this.setLocation((parent.getWidth() - this.getWidth()) / 2 + parent.getX(), (parent.getHeight() - this.getHeight()) / 2 + parent.getY());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new JPanel();
    jLabel = new JLabel();
    jTextField = new JTextField();
    jPanel2 = new JPanel();
    jButtonOk = new JButton();
    jButtonCancel = new JButton();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new Dimension(290, 90));
    getContentPane().setLayout(new BorderLayout(5, 5));

    jPanel1.setLayout(new GridLayout(2, 1, 5, 5));

    jLabel.setText("Имя:");
    jPanel1.add(jLabel);

    jTextField.setFont(new Font("Dialog", 0, 14));
    jTextField.addKeyListener(new KeyAdapter() {
      public void keyPressed(KeyEvent evt) {
        jTextFieldKeyPressed(evt);
      }
    });
    jPanel1.add(jTextField);

    getContentPane().add(jPanel1, BorderLayout.CENTER);

    jPanel2.setLayout(new GridLayout(1, 2, 5, 5));

    jButtonOk.setIcon(new ImageIcon(getClass().getResource("/Images/16x16/apply.png"))); // NOI18N
    jButtonOk.setText("ОК");
    jButtonOk.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jButtonOkActionPerformed(evt);
      }
    });
    jPanel2.add(jButtonOk);

    jButtonCancel.setIcon(new ImageIcon(getClass().getResource("/Images/16x16/cancel.png"))); // NOI18N
    jButtonCancel.setText("Отмена");
    jButtonCancel.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jButtonCancelActionPerformed(evt);
      }
    });
    jPanel2.add(jButtonCancel);

    getContentPane().add(jPanel2, BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
      String text = jTextField.getText();
      if (text.equals(""))
      {
        JOptionPane.showMessageDialog(this, "Введите имя домена", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
      }
      if (Frameset.getInstance().isDomen(domen, text))
      {
        JOptionPane.showMessageDialog(this, "Домен с таким именем уже существует", "Ошибка", JOptionPane.ERROR_MESSAGE);
        jTextField.selectAll();
        jTextField.requestFocusInWindow();
        return;
      }
      if (domen == null)
      {
        domen = new Domen(text);
        Frameset.getInstance().addDomen(domen);
      } else
      {
        domen.setName(text);
      }
//        ((JFrameMain) getParent()).setIsChange(true);
      this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldKeyPressed(KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
        jButtonOkActionPerformed(null);
      }
      if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
      {
        jButtonCancelActionPerformed(null);
      }
    }//GEN-LAST:event_jTextFieldKeyPressed

  public void run(String title, Domen domen)
  {
    this.setTitle(title);
    if (domen == null)
    {
      jTextField.setText("");
    } else
    {
      jTextField.setText(domen.getName());
    }
    jTextField.selectAll();
    this.domen = domen;
    setVisible(true);
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton jButtonCancel;
  private JButton jButtonOk;
  private JLabel jLabel;
  private JPanel jPanel1;
  private JPanel jPanel2;
  private JTextField jTextField;
  // End of variables declaration//GEN-END:variables
}
